### ISSUE TITLE
Use Key frame seek Increase seek speed

### ISSUE THREAD

**Issue by sudongg** [ffmpeginteropx/FFmpegInteropX#184] opened 2020-05-05 23:30 UTC
When playing some 2K or 4K video, seek will become very slow and even difficult to accept.
Only when playing some H264 encoded video, uwp mediaplayer will automatically use key frame seek.

I tried to get the next key frame with `av_seek_frame`  and `avformat_seek_file`, and set the ActualStartPosition to the next key frame time in `FFmpegInteropMSS::OnStarting`
`request->SetActualStartPosition(t);`

The key frame seek is basically implemented, and the speed of seek is greatly improved, but I wonder if there is a better way to implement it, or ffmpeg interopx has this function by default?

**Comment by lukasf** [comment] 2020-05-23 18:05
Hi @sudongg, I did some experiments with that long time ago. Not 100% sure how I did it exactly and I lost the sources of it. I think I used the normal av_seek_frame, then read packets until I got the first video packet, then used this packet's timestamp as actual start position. Is this similar to your solution?

I think it would be a good addition to have it in. However, it can make seek a lot more unprecise, depending on the file. I think it would be best if this can be dynamically turned of and off during playback. Then you could e.g. have fast seek when pressing "shift" during seek, or slow seek otherwise. So I think a property on the MSS instance would be good to toggle the seek behavior.

**Comment by sudongg** [comment] 2020-05-27 01:50
Hi @lukasf 
Yes, After using av_seek_frame, you need to get the next packet.

```
videoStream->GetNextSample();
currentAudioStream->GetNextSample();
```
This will get a new Video Stream Pts,which is the new actual start position I want to set

` request->SetActualStartPosition(VideoStreamPts)`

If you are using UncompressedVideoSampleProvider,
Cannot directly set ActualStartPosition,
Use avformat_seek_file seek seek to videoStream Pts, get HRESULT Time and set ActualStartPosition.

**Comment by lukasf** [comment] 2020-05-30 18:43
I think it is not a good idea to call GetNextSample just to get the PTS. Because that way, you will actually drop and lose the key frame that you wanted to show, which will cause problems with passthough streams. I think this is the reason why you need to call seek a second time.

When I played with this, I added a function to read (and enqueue) packets until the video stream has one, and then get the packet PTS from that packet without dequeueing it. Now the keyframe packet still is in the stream's queue and when GetNextSample gets called by the MSS engine, it will correctly deliver that keyframe packet.

**Comment by sudongg** [comment] 2020-05-31 01:17
@lukasf 
Yes, although I implemented keyframe seek, there are still many problems.

Although the key frame PTS can be obtained through GetNextSample, this PTS is not necessarily the next keyframe. If the seek time is less than the next keyframe time, it will even cause backward.
For most videos, the next video stream and audio stream must be obtained at the same time, otherwise the video will pause briefly.
For UncompressedVideoSampleProvider, seek is required twice.

Keyframe seek is a necessary function of modern player. I hope that the keyframe seek function can be added to FFmpegInteropX.

**Comment by sudongg** [comment] 2020-05-31 01:31
Since the implementation of keyframe seek is about two years ago, I can't recall all the changes I made. I made a lot of changes to ffmpeg interopx to solve various problems caused by using GetNextSample to get next keyframe.

If you can get next keyframe without GetNextSample, that would be great.

**Comment by sudongg** [comment] 2020-06-21 08:19
Hi @lukasf 
After using the fast seek branch, I found some problems.
1.I tested about 100 files, and most of them can use fast seek normally. However, for av01 and vp90 encoded videos, there is an image display error after seek.
sample link:
https://www.dropbox.com/s/0mksvgnq5bese26/KeyFrameSeekSample.zip?dl=0

2.Failure to find a key frame between the current time and seek time causes backsliding.
3.Some videos will pause a little after fast seek.
4.Seek speed is not the fastest. For 1080 avc1 format video, my project can achieve almost instant seek response. Although fast seek branch is also very fast, there will be a small amount of delay, which is not very smooth.

If problem 1 can be solved, fast seek is already available.
For question 2, I don't have a good way.
For question 3, I think it's because the audio key frame PTS is different from the video.

**Comment by lukasf** [comment] 2020-06-21 09:37
Hi @sudongg, thanks for the feedback.

1. I will look into these files.
2. I already have a solution for this. It is now available on the branch. If such a situation is detected, I do an additional seek to the next keyframe (forward seek instead of backward seek). This will add an additional delay, but it prevents the problematic seek behavior.
3. I also noticed this, not sure what it is caused by. It does not happen with all files. Maybe FastSeekCleanAudio=false would help, at the cost of possible audio glitch. This needs some investigation.
4. This could be caused by second seek for clean audio. You can try setting FastSeekCleanAudio=false in the config class. Do you play files from HDD or SSD? On HDD, the second seek could be noticeable.

**Comment by lukasf** [comment] 2020-06-24 09:46
I have checked the files you provided. I do not get any video for the AV1 file (maybe different FFmpeg build), but I could find and fix an issue with the VP9 sample. One of my timestamp checks assumed that samples always do have a duration. But the VP9 samples come without duration, which made my code accidentially drop the target keyframe. A fix is available now. Please check if this also solves the AV1 bug for you.

**Comment by sudongg** [comment] 2020-06-25 14:45
Hi @lukasf 
The AV1 format error has been resolved.
Problem 3 and  4, after using FastSeekCleanAudio = false, the problem has been significantly improved. Most videos can seek quickly, but not all videos can achieve the fastest seek speed (compared to my project).

In addition, there are some minor problems with quick search.
When changing the audio track, there will be a short pause in the video, my project not be paused.
This problem appears in the .mkv movie of AVC1. (I have no more samples)

When dragging the progress bar, some videos will switch between two key frames continuously, which will affect the visual effect.

**Comment by lukasf** [comment] 2020-06-27 20:38
I also noticed the problem with the progress bar. It is caused by my fix for problem 2. When dragging the slider, the someties we are switching between backward and forward keyframe seeking repeatedly. Not sure if we can fix problem 2 without this side effect, but I will look into it.

You are right, some videos now have a video pause after switching audio tracks. I think we have to disable fast seek after an audio track switch. Will look into this. But I don't understand why that does not happen with your solution...

**Comment by lukasf** [comment] 2020-06-28 10:59
I could solve the flicker issue by remembering the last seek direction and positions. As long as seeking happens between the last seek position and last seek actual, I keep the last seek direction. I also moved from av_seek_frame to avformat_seek_file, which allows me to get rid of the second seek (when switching from backward to forward seeking). The result looks very good and clean to me.

The only remaining problem is the video pause when switching audio tracks. For me it only happens noticeably with some files (probably those with large keyframe intervals), but then it is quite annoying. I tried to prevent FastSeek on the seek operation after SwitchStreams. But it does not work. The reason is that on stream switching, the engine somehow does two seek operations: One before SwitchStreams (which is totally unneccessary) and one after SwitchStreams. Preventing FastSeek on only the last seek operation does not solve the video pause. Only when both seek operations are done without FastSeek, then audio switching will be fast without video pause.

I remember that I already noticed this weird double seeking when working on DASH video stream switching. Theoretically, we could completely avoid the first seek (and maybe even the second one) if we'd switch streams through a custom API instead of using UWP APIs. If a switch stream was requested through our API, we could internally call the UWP APIs and then use our special handing for the next two seeks. But that would of course mean that apps have to implement their own stream selection UI and then trigger our API.

**Comment by sudongg** [comment] 2020-06-28 11:28
@lukasf 
I tested several videos and the problem of switching audio tracks has been resolved.
Most likely it is because you used avformat_seek_file.

**Comment by sudongg** [comment] 2020-06-28 12:33
Only when I use the UncompressedVideoSampleProvider will I use av_seek_frame for the first seek and avformat_seek_filefor the second seek, which I remember is necessary.

As for the problem of dragging the progress bar, now we will not switch between two keyframes, but I found some problems.
1.Some videos have a short pause when using `mediaElement.Position + TimeSpan.FromSeconds(5) ` to seek. (compared to my project)
Sample link:
https://www.dropbox.com/s/lu3nitt7kigss9c/seek%20pause%20sample.zip?dl=0

2.In the previous version, I can use the `mediaElement.Position - TimeSpan.FromSeconds(1)` And `mediaElement.Position + TimeSpan.FromSeconds(5)` Two consecutive keyframes are switched.
But this method invalid in the version after fix.
Moreover, in the case of pause play, If you successive to seek backwards and forwards, sometimes seek will fail and cannot seek forward or backward.
To reproduce this problem, you can add two buttons, add the function of seek forward or backward, and then press the two buttons continuously, which may trigger the problem.

**Comment by lukasf** [comment] 2020-06-28 19:23
### 1 Button seeking

After thinking this through, I don't believe that we can have a solution that works 100% clean for both mouse seek and button seek, unless we can somehow provide information about the kind of seeking that is happening.

Example: In a file, we seek forward to frame 5. It jumps to frame 10, because that is the next keyframe. Say this is a mouse seek. Now we drag the seekbar further to frame 6. We expect it to continue to show frame 10. Now imagine this as a keyboard/button seek. Again we seek forward to frame 5, again it jumps to frame 10. Now we press the "back" button, which will target frame 6. But this time, the user expects us to go back to frame 0 (first keyframe) instead of going forward to frame 10. From the user, this would be the logical way of working, but from the lib, both scenarios have the exact same seek order but different expected outcome:

Mouse: Seek (5) => Goto (10), Seek (6) => Goto 10
Button: Seek (5) => Goto (10), Seek (6) => Goto 0 (!)

How are we supposed to solve this? It's not possible without providing more information to the lib.

I managed to optimize my auto decision logic. Now at least it never gets stuck, because it kind of detects when you do get stuck and moves you further. But when switching seek direction (e.g. first forward, then backward), sometimes I still have to press the button twice to see an effect. The solution is a bit complicated and I am not sure yet if it is good approach. I will see if I can simplify it somehow. But there won't be a magic solution that solves the problem pointed out above, because that's just not possible. There is going to be some kind of downside no matter what we do, unless we provide some kind of "seek hint".

### 2. Stream switching

I still see slow stream switching on some files. I have implemented a solution that tries to detect stream switching. But it requires you to provide a PlaybackSession from MediaPlayer, so the lib can get access to playback position. It's not finished yet, still needs some optimizations.

### 3. Pause after seek

I can reproduce the problem. The pause always occurs with affected files, no matter if I do fast seeking, fast seeking with clean audio, or normal seeking. I looked into this but I don't have any idea where this comes from. The only strange thing on that file is that it has negative audio preroll (audio comes delayed, after video, which is pretty uncommon). I do handle that case now as well and cleanly drop audio packets until target position, still the pause occurs, no change at all. You say that it does not happen with your solution? If you can make the sources available, I could try to find out what is the difference.

**Comment by lukasf** [comment] 2020-07-02 20:01
I checked in my latest changeset that improves button seeking and stream switching. As I said, it will not solve all problems. We won't get 100% clean seeking unless we tell the lib upfront about the seek that is going to happen.

I spent some more time with the "pause after seek" issue, but I give up now. I really don't have any clue what is happening there. All timestamps look fine, everything comes in sync, still there is this pause. Luckily, most files work fine, only few are affected. And we have not made things worse, there pause was already there before our changes...

**Comment by sudongg** [comment] 2020-07-03 04:13
@lukasf 
1 Button seeking
I don't use MediaElement, so I can change the seek mode when I drag the progress bar or press the key.
I add a StepFastSeek variable in Config to change the seek mode. 
(However, I don't know why, after changing this value constantly, parameter passing errors often occur.)

If use MediaElement, may be able to open StepFastSeek when you press seek button, and close StepFastSeek when the seek complete event.

2. Stream switching
I don't have any more sample tests, but all my samples here have passed.

 3. Pause after seek
I am trying to update my project, but I only replaced GetNextPacket with GetNextPacketTimestamp, and this problem occurs.
You can try to get the timestamp from getnextpacket to find out the difference between the two, which may solve this problem.

After replacing getnextpacket with getnextpackettimestamp, only problem 3 has been found.
I don't feel the difference in seek speed. Some of the videos I mentioned earlier are not as fast as my project seek, not because I used GetNextPacket , but I don’t know why, maybe I didn't use MediaElement.

**Comment by lukasf** [comment] 2020-07-15 17:47
I played quite some time with this pause after seek. I verified that all timestamps are 100% correct with my solution. It is your solution that has incorrect timestamps: You get the timestamp from the first sample, but that sample is then discarded. So when playback starts, you actually return the next sample, which has a different timestamp than what you used with SetActualPosition. I can simulate that if I subtract the sample duration from my timestamp before calling SetActualPosition. For strange reasons, it really seems to improve the behavior with this file. But I don't think it would be a good idea to add this. That file plays strangely anyways. After a seek, first it plays too slow, then catches up fast, then normal playback. If I add 8 sample durations to the actual position, playback is fluid. But these are all weird workarounds, just there to improve a few strange files, probably making playback worse with other files.

**Comment by sudongg** [comment] 2020-07-16 06:26
@lukasf 
My solution is very different from your solution, not just in my use of GetNextPacket.
However, these are not important, I only care about the final actual user experience, I want the fastest fast speed, the best seek experience.
If I can't solve the problem of Pause after seek, I can't replace GetNextPacket  with GetNextPacketTimestamp because it will affect the user experience.
Even if you can prove that the timestamps you got is correct, some videos will still pause after seek.

Some audio stream timestamps are different from video stream timestamps, which may cause pause after seek. Even if you make a correction, it may still pause after seek. At this time, if I try to use the timestamps of the audio stream directly, it will not pause, But not all videos are valid.
According to the above situation, if you want to solve pause after seek, your timestamps must not only be correct, but also need to decide whether to use audio timestamps or video timestamps according to different files.

Currently I still use getnextpacket, plus some of your solutions, the fast seek experience is very good.
What I need to solve now is the problem that the FFmpegInteropConfig parameter transfer mentioned before may go wrong. I don’t know whether the FFmpegInteropConfig parameter can be modified dynamically.

**Comment by lukasf** [comment] 2020-07-16 15:28
It is really hard to compare my solution to a solution that I cannot try myself and cannot see the source code of. I have replaced GetNextPacketTimestamp with GetNextPacket and I saw some improvement of seek time for this specific file. I can get similar behavior if I use GetNextPacketTimestamp and then subtract a sample duration from the timestamp. Then my ActualPosition is before the "real" actual position of the first video packet, much like in your solution. I can't explain why that helps, and I have not yet found out which files need the start time offset and which don't. Additionally, I drop all audio packets until the audio stream is at the same position as the video stream (or short before that position). I have experimented with using the audio stream position for SetActualPosition instead of the video stream position, but I did not see improvements there.

I did not yet understand the problem you have with config parameter setting. We don't use any locking or any other special logic in the config class properties, so I cannot imagine what might cause trouble setting those values. What kind of errors occur? Do you have an exception and stack trace?

**Comment by lukasf** [comment] 2020-07-24 20:31
I have noticed that some of my optimizations were not pushed to the branch. I have updated it now. It might improve the seek behavior for you.

**Closed** 2020-09-04 06:22 UTC
