### ISSUE TITLE
Reinitialization FrameGrabber Thrown Exception

### ISSUE THREAD

**Issue by yhrgsp** [ffmpeginteropx/FFmpegInteropX#284] opened 2022-08-02 11:18 UTC
hi,
when I tried to release the FrameGrabber with the Dispose method or initialize it again I get this error:
Exception thrown at 0x13C9768C (FFmpegInteropX.dll) in MyApp.exe: 0xC0000005: Access violation writing location 0x00000014

    FrameGrabber fg = await FrameGrabber.CreateFromUriAsync(@"udp://192.168.1.12:1234");
     while (play) {
                 VideoFrame videoData = await fg.ExtractNextVideoFrameAsync();
                 // do some work
    }
    fg.Dispose(); //Thrown Exception
    FrameGrabber fg2 = await FrameGrabber.CreateFromUriAsync(@"udp://192.168.1.25:5009"); 

or:

        FrameGrabber fg = await FrameGrabber.CreateFromUriAsync(@"udp://192.168.1.12:1234");
         while (play) {
                     VideoFrame videoData = await fg.ExtractNextVideoFrameAsync();
                     // do some work
        }
        FrameGrabber fg2 = await FrameGrabber.CreateFromUriAsync(@"udp://192.168.1.25:5009"); //Thrown Exception

thanks

**Comment by brabebhin** [comment] 2022-08-02 18:08
Hi,

I don't have access to my PC right now, but does this also happen if you do the same with a file on disk?

**Comment by yhrgsp** [comment] 2022-08-03 10:06
> Hi,
> 
> I don't have access to my PC right now, but does this also happen if you do the same with a file on disk?

In the sample its work fine, but it work with "FrameGrabber.CreateFromStreamAsync()" and I use "FrameGrabber.CreateFromUriAsync()".

**Comment by brabebhin** [comment] 2022-08-03 20:44
If you attach a native debugger, do you get anything in the output window?

**Comment by yhrgsp** [comment] 2022-08-04 07:02
> If you attach a native debugger, do you get anything in the output window?

I get this:
Exception thrown at 0x00007FFC38DE1F70 (FFmpegInteropX.dll) in App6.exe: 0xC0000005: Access violation writing location 0x0000000000000028.

**Comment by brabebhin** [comment] 2022-08-04 09:22
Ok
I will try to reproduce.

**Comment by brabebhin** [comment] 2022-08-04 14:12
I tried reproducing and couldn't.

Can you describe your exact setup?

Thanks.

**Comment by brabebhin** [comment] 2022-08-04 18:08
I mean what servers you use for setting up the udp streaming.

**Comment by yhrgsp** [comment] 2022-08-04 18:45
> I mean what servers you use for setting up the udp streaming.

It happens with every url, for example:
"http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"

If I try to call framegrabber.dispose or if I call framegrabber again Its thrown me exception.

**Comment by brabebhin** [comment] 2022-08-05 07:31
Are you using nuget package for ffmpeginteropx or referencing the project directly?

**Comment by yhrgsp** [comment] 2022-08-05 07:51
> Are you using nuget package for ffmpeginteropx or referencing the project directly? Anyway, check out #285, I adapted the samples to allow frame grabbing from Uri.
> 
> It still works fine for me with the uri you provided.

I'm using nugget package.

**Comment by yhrgsp** [comment] 2022-08-05 09:34
> > Are you using nuget package for ffmpeginteropx or referencing the project directly? Anyway, check out #285, I adapted the samples to allow frame grabbing from Uri.
> > It still works fine for me with the uri you provided.
> 
> I'm using nugget package.

Are you using nuget package or referencing the project directly?

**Comment by brabebhin** [comment] 2022-08-05 09:58
I am referring the project directly, so that i can debug.
I only use nuget for the ffmpeg build.

**Comment by yhrgsp** [comment] 2022-08-05 13:00
hi,
I tried the sample you just released and the its thrown me the same exception again.
but when I downgrade from version 1.0.1 to 1.0.0 its works perfectly fine!

**Comment by brabebhin** [comment] 2022-08-05 14:19
Ok good to know. Can you obtain any stack traces from the c++ sample?

**Comment by yhrgsp** [comment] 2022-08-05 14:36
> Ok good to know. Can you obtain any stack traces from the c++ sample?

Yes, but only after the weakened. I'm without my laptop.

**Comment by brabebhin** [comment] 2022-08-05 15:08
I still couldn't reproduce even with the code that's in 1.0.1
Regardless, that code is pretty old and ancient by now.

I am going to push a pre-release nuget which is a snapshot of master.

**Comment by brabebhin** [comment] 2022-08-05 15:32
right so I uploaded a new nuget package from master. 1.0.2-pre, you will need to enable prerelease nuget versions to see it.

**Comment by yhrgsp** [comment] 2022-08-05 15:45
> right so I uploaded a new nuget package from master. 1.0.2-pre, you will need to enable prerelease nuget versions to see it.

Ok, I'll try it.
One more question,
How do I use multiple instance of framegrabber?

**Comment by brabebhin** [comment] 2022-08-05 16:07
Simply create multiple instances of them. There is nothing that makes them singleton. Just make sure they don't have the same underlaying stream, that might have funny results.

**Comment by yhrgsp** [comment] 2022-08-07 17:39
> Simply create multiple instances of them. There is nothing that makes them singleton. Just make sure they don't have the same underlaying stream, that might have funny results.

Thanks,
I'll try it.

**Comment by yhrgsp** [comment] 2022-08-10 10:46
> right so I uploaded a new nuget package from master. 1.0.2-pre, you will need to enable prerelease nuget versions to see it.


Why do you remove from VideoFrame the Dispose method in ver 1.0.2?

**Comment by brabebhin** [comment] 2022-08-10 11:03
Ooups.a bug. I'll fix it ASAP. Does this version fix the framegrabber issue?

**Comment by yhrgsp** [comment] 2022-08-10 11:20
Yes.

**Comment by brabebhin** [comment] 2022-08-10 13:35
Actually there is no need for IDisposable in VideoFrame now. 
1.0.2 contains our code base generated from c++/winRT migration, this will have a bunch of breaking changes.

if @lukasf  agrees, I can put that back in IDL for binary compatibility, but that would bloat our code base.

**Comment by lukasf** [comment] 2022-08-10 18:07
@brabebhin Did you do any actual library changes for your 1.0.2-pre package? I have not yet understood how you fixed this, and the PR I see opened only adds code to the sample apps.

I think it would be good to keep the Dispose method on the VideoFrame. Otherwise, people would have to dispose the PixelData property of the VideoFrame to free up memory, which is much less intuitive.

**Comment by lukasf** [comment] 2022-08-10 18:26
Okay it looks like I actually introduced this, by adding this to FFmpegMediaSource destructor, without checking avIOCtx for NULL:

  ```
  avIOCtx->opaque = NULL;
    avio_closep(&avIOCtx);
```

On master branch, we have a NULL check so it does not occur there. So no changes are required, fix will be automatically part of the next official release.

**Comment by brabebhin** [comment] 2022-08-10 19:46
I haven't made any changes, 1.0.2 pre is a snapshot of master.

The idisposable is not needed. We can't delete the PixelData anymore cause it isn't a pointer/handle anymore.

I suspected that was the issue but couldn't reproduce even when the 1.0.1 snapshot.

**Comment by lukasf** [comment] 2022-08-11 18:38
Fact is that the VideoFrame holds a considerable amount of memory, and we must provide a way to release it from C#, using IDisposable. I will look into this when I am back.

**Comment by brabebhin** [comment] 2022-08-13 07:10
True.  Probably casting to IUknown and calling Release should work.

**Comment by lukasf** [comment] 2022-08-21 21:56
Closing this. The exception is solved on master branch, and disposable VideoFrame just got merged as well.

**Closed** 2022-08-21 21:56 UTC
