### ISSUE TITLE
It suddenly stops while playing an online video

### ISSUE THREAD

**Issue by yikuo123** [ffmpeginteropx/FFmpegInteropX#317] opened 2022-10-20 15:55 UTC
Just like #238.

I tried FFmepgInteropX version 0.9.4, 1.0.1 and 1.1.0-pre24, but all of them are the same. A few minutes later (about 3 minutes), MediaPlayer will stop and the timeline just jump to the end.

I also tried playing video with the original `Windows.Media.Core.MediaSource` and it's ok.

``` C#
public sealed partial class MainPage : Page
{
    private MediaPlayer _mediaPlayer;
    private FFmpegMediaSource _currentMediaSource;

    public MainPage()
    {
        this.InitializeComponent();
        this.Loaded += MainPage_Loaded;
    }

    private async void MainPage_Loaded(object sender, RoutedEventArgs e)
    {
        _mediaPlayer = new MediaPlayer();
        _mediaPlayer.AutoPlay = true;
        _mediaPlayer.AudioCategory = MediaPlayerAudioCategory.Movie;
        MyMediaPlayerElement.SetMediaPlayer(_mediaPlayer);
        
        var url = @"https://f.video.weibocdn.com/o0/VbwYocF4lx0808KL6sCQ01041200LhGB0E010.mp4?label=mp4_hd&template=852x480.25.0&ori=0&ps=1BThihd3VLAY5R&Expires=1666285374&ssig=IpiL%2BhhyCq&KID=unistore,video";
        _currentMediaSource = await FFmpegMediaSource.CreateFromUriAsync(url, new MediaSourceConfig {
            VideoDecoderMode = FFmpegInteropX.VideoDecoderMode.ForceSystemDecoder,
        });
        _mediaPlayer.Source = _currentMediaSource.CreateMediaPlaybackItem();
    }
}
```

> The URL in demo may become invalid. But URL is not important, I tried about 10 online videos and they are all the same.
> I'm not sure how long it will reproduce but it will.
> If the URL becomes invalid, you can get a new one by playing video at [this link](https://m.weibo.cn/detail/4826778050234911) and right click to copy a new URL.

**Comment by lukasf** [comment] 2022-10-20 17:17
The URL is invalid and I also cannot play any videos on that site without creating an account and logging in. Please check the debug output and post end of output. I guess we either get EOF, or there is some error. Debug output might help identifying the issue.

You could also check the FormatInfo property to see which streaming format is used. We might be able to find a similar sample stream from a site that does not require registration.

I have been seeing EOF in rtsp streams (#280). There was not much I could do about that. It was FFmpeg reporting EOF and there was no way of recovering.

**Comment by lukasf** [comment] 2022-10-20 18:37
Does the problem also occur when playing the downloaded file? I'd guess it only happens when playing through streaming. I have played the downloaded file twice and it plays fine till the end.

Our lib, as well as ffmpeg will write debug output that can be seen in VS output window while debugging the app.

This is what I see in VS on end of local file playback:

```
GetNextSample
GetNextPacket reaching EOF
End of stream reached. Enter draining mode.
GetNextSample
GetNextSample
End of stream reached. No more samples in decoder.
End of stream reached.
DisableStream
Flush
The thread 0x3690 has exited with code 0 (0x0).
The thread 0x3c58 has exited with code 0 (0x0).
The thread 0x584c has exited with code 0 (0x0).
```

VLC has its own custom stream parsing and download implementation. It only uses FFmpeg for the actual decoding. That is why you cannot really compare VLC to our lib when it comes to streaming scenarios. You should rather use ffplay for comparison, since it will also use FFmpeg for stream parsing  (and best use the exact same version that we are using as a lib).

**Comment by brabebhin** [comment] 2022-10-20 19:04
I think (might be mistaken) that you need either mixed or native debugger to see that output.

**Comment by brabebhin** [comment] 2022-10-21 05:56
I also noticed some video files suddenly becoming very choppy or outright video playback freezes, and this happens on local files. I too suspect the latest ffmpeg is a bit flimsy.

**Comment by lukasf** [comment] 2022-10-21 18:29
It sounds like the server just drops the connection occasionally (or sends response data too late / timeout). The ffplay.exe you have use gnutls for https, ours use openssl for https, when using http, it is ffmpeg internal http handler. If all these three handlers show the same behavior, then it is probably just an unreliable server.

I found these ffmpeg options, which sound like they could help:

reconnect_at_eof

    If set then eof is treated like an error and causes reconnection, this is useful for live / endless streams.
reconnect_streamed

    If set then even streamed/non seekable streams will be reconnected on errors.
reconnect_on_network_error

    Reconnect automatically in case of TCP/TLS errors during connect.
reconnect_on_http_error

    A comma separated list of HTTP status codes to reconnect on. The list can include specific status codes (e.g. ’503’) or the strings ’4xx’ / ’5xx’.
reconnect_delay_max

    Sets the maximum delay in seconds after which to give up reconnecting


Put these to FFmpegOptions in our config class with value "1" to enable an option. Not sure if this will help, but it sounds like you can use them so ffmpeg will retry transmission on error or incorrect eof.

**Comment by lukasf** [comment] 2022-10-21 19:25
Oh and for streaming I'd recommend trying the new ReadAheadBuffer in our lib (enable it in the config class). This will download and buffer a configurable amount of data, to allow uninterrupted playback of streams. This is available in the latest prerelease nuget package.

**Comment by lukasf** [comment] 2022-10-23 19:26
Cool, this is really good to hear! Yes I think we should add a readme section for streaming, and describe the recommended parameters.

**Comment by lukasf** [comment] 2022-11-21 20:43
Closing this, since the issue is solved and documentation has been added.

**Closed as completed by lukasf** 2022-11-21 20:43 UTC
