### ISSUE TITLE
RTMPS "Error HRESULT E_FAIL has been returned from a call to a COM component"

### ISSUE THREAD

**Issue by dangphan** [ffmpeginteropx/FFmpegInteropX#241] opened 2021-05-27 09:45 UTC
Hi all,

When I open a **RTMPS** url ,it throw an Exception :"Error HRESULT E_FAIL has been returned from a call to a COM component. 
But when I test a RTMP url, it is working normally.
Why don't support **RTMPS**?
How can I solve this problem??

![image](https://user-images.githubusercontent.com/4945587/119917367-a044ee80-bf90-11eb-8130-22c4d2dffe6c.png)

**Comment by brabebhin** [comment] 2021-05-27 12:02
I think this is related to integrating openSSL or similar SSL libs in ffmpeg for UWP

**Comment by dangphan** [comment] 2021-05-28 01:54
> I think this is related to integrating openSSL or similar SSL libs in ffmpeg for UWP

Thank you for your instruction.
Could you tell me how to configure SSL libs in ffmpeg for UWP?

I used VLC with above RTMPS url is OK.
![image](https://user-images.githubusercontent.com/4945587/119918214-39c0d000-bf92-11eb-9ad4-102ca1623739.png)

**Comment by brabebhin** [comment] 2021-05-28 10:21
This is a long standing issue on our side. See #206

**Comment by lukasf** [comment] 2021-09-23 18:26
Closing this as duplicate of #206.

**Closed by lukasf** 2021-09-23 18:26 UTC
