### ISSUE TITLE
Get media stream by using rtmps protocal

### ISSUE THREAD

**Issue by tamsps** [ffmpeginteropx/FFmpegInteropX#240] opened 2021-05-19 01:56 UTC
I'm using CreateFFmpegInteropMSSFromUri(uri, true, true) method to load media stream from server. Server stream video both RTMP and RTMPS protocal.  If I set URI = **rtmp**://xxx.xxx then method return was not null, But if I change URI = **rtmps**://xxxx.xxx then method return null.
How can I get media by using RTMPS protocal?
Thank you,
Tam

**Comment by lukasf** [comment] 2021-09-23 18:32
Sorry for the late response, I somehow missed this issue. It currently fails because we don't have openssl in FFmpeg build. This is why we don't support the secure/encrypted transport protocols. This is a long standing issue and covered in #206. There were technical, as well as licensing issues that prevented us from integrating openssl in the past.

Openssl 3.0 has a new, much better license and technical improvements, which should make it possible to integrate it. I have recently started working on this, please follow #206 for updates if you are still interested.

Closing this one as duplicate of #206.

**Closed by lukasf** 2021-09-23 18:32 UTC

**Comment by lukasf** [comment] 2022-01-12 09:39
Openssl is now available in FFmpegInteropX 0.9.3!
