### ISSUE TITLE
It always crashes after resetting the Source of MediaPlayer in UWP.

### ISSUE THREAD

**Issue by yikuo123** [ffmpeginteropx/FFmpegInteropX#314] opened 2022-10-13 10:20 UTC
It always crashes after resetting the `Source` of MediaPlayer in UWP.

FFmpegInteropX version: 5.1.100
FFmepgInteropX.UWP version: 1.0.1

Code as following:

``` C#
string url = "https://samples.mplayerhq.hu/Matroska/subtitles/multiple_sub_sample.mkv";

FFmpegInteropX.FFmpegMediaSource streamMediaSource = await FFmpegInteropX.FFmpegMediaSource.CreateFromUriAsync(url);
streamMediaPlayer.Source = streamMediaSource.CreateMediaPlaybackItem();
streamMediaPlayer.Play();

await Task.Delay(10 * 1000);

streamMediaSource = await FFmpegInteropX.FFmpegMediaSource.CreateFromUriAsync(url);
streamMediaPlayer.Source = streamMediaSource.CreateMediaPlaybackItem();
streamMediaPlayer.Play();
```

The second Method Play() will crash after a few seconds whatever the new url is.
```
Exception thrown at 0x00007FFAE8C71F70 (FFmpegInteropX.dll) in app.exe: 0xC0000005: Access violation writing location 0x0000000000000028.
```

**Comment by brabebhin** [comment] 2022-10-14 14:04
You need to wait for the media opened event in order to call play. That task delay is likely causing some timimg issues.

**Comment by lukasf** [comment] 2022-10-14 15:54
I think the problem ist that you do not keep reference to the first FFmpegMediaSource while the second one is being opened by MediaPlayer. MediaPlayer will keep playing the first source until you received either opened or failed for the second source. So you must keep reference to the first source during opening the second source. If you check our samples, you will see that we actually have two fields for FFmpegMediaSource. One is for the currently playing, and one is for the next one that is being opened. One field will be nulled out after Opened or Failed event from MediaPlayer. Only then we can safely release references to the previous file.

If you don't properly keep reference, you will run into access violations, which is what you see.

**Comment by brabebhin** [comment] 2022-10-15 08:48
Please provide a complete code sample that reproduces the issue.

**Comment by brabebhin** [comment] 2022-10-18 14:17
`public sealed partial class MainPage : Page
    {
        private MediaPlayer _mediaPlayer;
        private FFmpegMediaSource _lastMediaSource;
        private FFmpegMediaSource _currentMediaSource;

        public MainPage()
        {
            this.InitializeComponent();
            this.Loaded += MainPage_Loaded;
        }

        private async void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            _mediaPlayer = new MediaPlayer();
            _mediaPlayer.AutoPlay = true;
            _mediaPlayer.AudioCategory = MediaPlayerAudioCategory.Movie;
            _mediaPlayer.MediaOpened += MediaPlayer_MediaOpened; ;
            _mediaPlayer.MediaFailed += MediaPlayer_MediaFailed; ;
            MyMediaPlayerElement.SetMediaPlayer(_mediaPlayer);

            await Play();
        }

        private async void MediaPlayer_MediaOpened(MediaPlayer sender, object args)
        {
            await Task.Delay(3000);
            await Play();
        }

        private async void MediaPlayer_MediaFailed(MediaPlayer sender, MediaPlayerFailedEventArgs args)
        {
            await Task.Delay(3000);
            await Play();
        }

        private async Task Play()
        {
            await PlayValidMediaSource();
            //PlayInvalidMediaSource();
        }

        // Scenario 1, Playing valid media source, throws uncaughtable exception "Access violation"
        private async Task PlayValidMediaSource()
        {
            //_lastMediaSource?.Dispose(); // this also throws uncaughtable exception, ignore it now
            _lastMediaSource = _currentMediaSource;

            _currentMediaSource = await FFmpegMediaSource.CreateFromUriAsync(@"http://www.w3school.com.cn/example/html5/mov_bbb.mp4");
            _mediaPlayer.Source = _currentMediaSource.CreateMediaPlaybackItem();
        }

        // Scenario 2: Playing invalid media source, throws uncaughtable exception "Access violation"
        private async void PlayInvalidMediaSource()
        {
            try
            {
                var mediaSource = await FFmpegMediaSource.CreateFromUriAsync("https://example.com/");
                _mediaPlayer.Source = mediaSource.CreateMediaPlaybackItem();
            }
            catch (Exception e)
            {
                //FIXME: This code block can not catch "Access violation" exception!
                Debug.WriteLine($"Invalide media source, error={e}");
            }
        }
    }`

I took the liberty to slightly modify your code. Can you try this version and see how it works out?
Remember not to Dispose an active MediaSource.

**Comment by lukasf** [comment] 2022-10-18 18:38
Hi @yikuo123,

thanks for providing the samples. Indeed I could reproduce the crashes here. It is a problem of accessing an AVIOContext field in the destructor without having a NULL check in there. This is already fixed on master branch, but I was not aware that this totally breaks all streaming/URL sources (since AVIOContext is never assigned in that scenario).

This is a pretty bad one, sorry for the inconvenience. We might have to release a 1.0.2 quickfix for this, because it will take a while until we create the next major release from master branch.

@brabebhin This makes me think about trying to re-activate unit tests once again. We would not have this bug, if our AppVeyor build would automatically execute at least a few basic tests. I have been thinking, can't we replace those damn unreliable UWP unit tests with a plain .NET Core unit test project? I mean, we don't really need any UI or app running, just to create our FFmpegMediaSource, right? We don't need UWP either (at least not our C++/WinRT version on master branch). I might give this a try in the next days.

**Comment by brabebhin** [comment] 2022-10-18 18:53
I think our current master branch will fix the issue. I had trouble reproducing it cause the url would sporadically become unavailable. I couldn't confirm 1000% though.

As for unit tests, this is a tough one. I think we still need a full UWP environment for some APIs to work.

**Closed as completed** 2023-04-06 08:33 UTC
